crnn_config:
    input_shape: 6
    batch_size: 64
    epochs: 15
    output_shape: 7
    l2_reg: 0.01
    cnn_activations: relu
    lstm_units: 100
    lstm_dropout: 0.1
    lstm_recurrent_dropout: 0.1
    conv_kernel_size: 7
    conv_filters: 128
    conv_padding: valid
    maxpooling_size: 2
    loss: categorical_crossentropy
    optimizer: adam
data_generation:
    tfrecord_destination: './data/tfrecords/'
    tfrecord_windows_destination: './data/tfrecord_windows/'
    window_size: 100
    window_shift_length: 10
    train_file_pattern:
    - './data/tfrecord_windows/subject_[1-5]_*.tfrecord'
    - './data/tfrecord_windows/subject_[89]_*.tfrecord'
    validation_file_pattern:
    - './data/tfrecord_windows/subject_[67]_*.tfrecord'
    test_file_pattern:
    - './data/tfrecord_windows/subject_10_*.tfrecord'
evaluation:
    log_dir: "./logs/"

