crnn_config:
    input_shape:
    - 100
    - 6
    batch_size: 128
    epochs: 5
    shuffle_buffer_size: 2000
    l2_reg: 0.01
    cnn_activations: relu
    lstm_units: 100
    lstm_dropout: 0.1
    lstm_recurrent_dropout: 0.1
    conv_kernel_size: 7
    conv_filters: 128
    conv_padding: valid
    maxpooling_size: 2
    loss: categorical_crossentropy
    optimizer: adam
    class_names:
    - "PEL"
    - "ABD"
    - "FEL"
    - "IR"
    - "ER"
    - "TRAP"
    - "ROW"
data_generation:
    tfrecord_windows_destination: './tmp/tfrecord_windows/'
    window_size: 100
    window_shift_length: 50
    train_csv_file_pattern:
    - './datasets/spar_csv/S[1-9]_*.csv'
    - './datasets/spar_csv/S1[0-6]_*.csv'
    validation_csv_file_pattern:
    - './datasets/spar_csv/S1[7-9]_*.csv'
    - './datasets/spar_csv/S20_*.csv'
evaluation:
    log_dir: "./reports/logs/"
    weights_file: "reports/logs/logs_2021_11_18_00_14_40/checkpoint_12.tf"
visualization:
    view_columns: False
    view_trajectories: True
    csv_file_patterns: 
    - './datasets/spar_csv/S10_E[0-6]_L.csv'
    num_view_steps: 1000

